[changelog]
header = """
# Changelog
"""

body = """
{% if version -%}
## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
## [Unreleased]
{% endif -%}

{% for group, commits in commits | filter(attribute="merge_commit", value=false) | group_by(attribute="group") %}
{% if group != "<!-- 9 -->MDK" %}
### {{ group | striptags | trim }}
{% for commit in commits %}
- {% if commit.scope %}{% for scope in commit.scope | split(pat=",") %}`{{ scope | trim }}`{% if not loop.last %}, {% endif %}{% endfor %}: {% endif %}{{ commit.message | split(pat="\n") | first | trim }}\
{% if commit.remote.pr_number %} in [#{{ commit.remote.pr_number }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/pull/{{ commit.remote.pr_number }}){%- endif -%}
{% endfor %}
{% endif %}
{% endfor %}
"""

trim = true

[git]
conventional_commits = true
filter_unconventional = true
require_conventional = false
filter_commits = true
protect_breaking_commits = true
tag_pattern = "v[0-9].*"
topo_order = false
sort_commits = "newest"

commit_preprocessors = [
  { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "" },
]

commit_parsers = [
  { message = "^mdk", group = "<!-- 9 -->MDK" },
  { field = "breaking", pattern = "true", group = "<!-- 0 -->Breaking Changes" },
  { message = "^feat", group = "<!-- 1 -->Added" },
  { message = "^fix", group = "<!-- 2 -->Fixed" },
  { message = "^perf", group = "<!-- 3 -->Performance" },
]
