org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


## Mod Properties
modId=tsukichat
modName=Tsuki Chat
modLicense=MIT
modGroupId=net.meatwo310.tsukichat
modAuthors=Meatwo310
modDescription=Converts Romaji to Japanese in chat.
modDisplayUrl=https://github.com/Meatwo310/tsuki-chat
modIssueTrackerUrl=https://github.com/Meatwo310/tsuki-chat/issues
modCredits=


## Fabric Mod Properties
modFabricEnvironment=*
modFabricEntrypoint=net.meatwo310.tsukichat.ModMain
modFabricClientEntrypoint=net.meatwo310.tsukichat.client.ModClient
