
name: Publish to Modrinth and CurseForge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-id: TT8G3XmI
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1029553
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}